name: islamic_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  easy_localization: ^3.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/files/
    - assets/translations/



  fonts:
    - family: ElMessiri
      fonts:
        - asset: fonts/ElMessiri-Regular.ttf


